In [1]:
import pandas as pd

In [27]:
network_data = pd.read_csv('Data/UNSW-NB15_1.csv', header=None)

/home/awantik/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (1,3,47) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
network_data.head()

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,59.166.0.0,1390,149.171.126.6,53,udp,CON,0.001055,132,164,31,...,0,3,7,1,3,1,1,1,NaN,0
1,59.166.0.0,33661,149.171.126.9,1024,udp,CON,0.036133,528,304,31,...,0,2,4,2,3,1,1,2,NaN,0
2,59.166.0.6,1464,149.171.126.7,53,udp,CON,0.001119,146,178,31,...,0,12,8,1,2,2,1,1,NaN,0
3,59.166.0.5,3593,149.171.126.5,53,udp,CON,0.001209,132,164,31,...,0,6,9,1,1,1,1,1,NaN,0
4,59.166.0.3,49664,149.171.126.0,53,udp,CON,0.001169,146,178,31,...,0,7,9,1,1,1,1,1,NaN,0

In [10]:
schema = pd.read_csv('Data/NUSW-NB15_features.csv', encoding='latin', index_col='No.')

In [14]:
columns = schema.Name.to_list()

In [28]:
network_data.columns = columns

In [29]:
network_data.head()

,srcip,sport,dstip,dsport,proto,state,dur,sbytes,dbytes,sttl,...,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
0,59.166.0.0,1390,149.171.126.6,53,udp,CON,0.001055,132,164,31,...,0,3,7,1,3,1,1,1,NaN,0
1,59.166.0.0,33661,149.171.126.9,1024,udp,CON,0.036133,528,304,31,...,0,2,4,2,3,1,1,2,NaN,0
2,59.166.0.6,1464,149.171.126.7,53,udp,CON,0.001119,146,178,31,...,0,12,8,1,2,2,1,1,NaN,0
3,59.166.0.5,3593,149.171.126.5,53,udp,CON,0.001209,132,164,31,...,0,6,9,1,1,1,1,1,NaN,0
4,59.166.0.3,49664,149.171.126.0,53,udp,CON,0.001169,146,178,31,...,0,7,9,1,1,1,1,1,NaN,0

In [17]:
network_data.select_dtypes(include=['object'])

,srcip,sport,dstip,dsport,proto,state,service,attack_cat
0,59.166.0.0,1390,149.171.126.6,53,udp,CON,dns,NaN
1,59.166.0.0,33661,149.171.126.9,1024,udp,CON,-,NaN
2,59.166.0.6,1464,149.171.126.7,53,udp,CON,dns,NaN
3,59.166.0.5,3593,149.171.126.5,53,udp,CON,dns,NaN
4,59.166.0.3,49664,149.171.126.0,53,udp,CON,dns,NaN
5,59.166.0.0,32119,149.171.126.9,111,udp,CON,-,NaN
6,59.166.0.6,2142,149.171.126.4,53,udp,CON,dns,NaN
7,10.40.182.3,0,10.40.182.3,0,arp,INT,-,NaN
8,59.166.0.5,40726,149.171.126.6,53,udp,CON,dns,NaN
9,59.166.0.7,12660,149.171.126.4,53,udp,CON,dns,NaN
10,10.40.170.2,0,10.40.170.2,0,arp,INT,-,NaN
11,10.40.170.2,0,10.40.170.2,0,arp,INT,-,NaN
12,10.40.182.3,0,10.40.182.3,0,arp,INT,-,NaN
13,59.166.0.1,48847,149.171.126.5,53,udp,CON,dns,NaN
14,59.166.0.1,24266,149.171.126.9,41049,udp,CON,-,NaN
15,59.166.0.1,10393,149.171.126.6,44307,udp,CON,-,NaN
16,59.166.0.2,62539,149.171.126.4,53,udp,CON,dns,NaN
17,59.166.0.1,21270,149.171.126.9,111,udp,CON,-,NaN
18,59.166.0.1,8989,149.171.126.6,111,udp,CON,-,NaN
19,59.166.0.4,49346,149.171.126.5,53,udp,CON,dns,NaN
20,175.45.176.3,21223,149.171.126.18,32780,udp,INT,-,Exploits
21,175.45.176.2,23357,149.171.126.16,80,tcp,FIN,http,Exploits
22,175.45.176.0,13284,149.171.126.16,80,tcp,FIN,http,Reconnaissance
23,59.166.0.3,4192,149.171.126.9,53,udp,CON,dns,NaN
24,59.166.0.2,26872,149.171.126.8,53,udp,CON,dns,NaN
25,59.166.0.8,24946,149.171.126.2,53,udp,CON,dns,NaN
26,59.166.0.9,5685,149.171.126.6,53,udp,CON,dns,NaN
27,59.166.0.0,22848,149.171.126.1,53,udp,CON,dns,NaN
28,59.166.0.5,28565,149.171.126.9,53,udp,CON,dns,NaN
29,59.166.0.7,46719,149.171.126.4,53,udp,CON,dns,NaN
...,...,...,...,...,...,...,...,...
699971,59.166.0.1,46807,149.171.126.1,80,tcp,FIN,-,NaN
699972,59.166.0.7,60323,149.171.126.1,5190,tcp,FIN,-,NaN
699973,59.166.0.9,65260,149.171.126.3,143,tcp,FIN,-,NaN
699974,59.166.0.0,36648,149.171.126.8,53,udp,CON,-,NaN
699975,59.166.0.3,14404,149.171.126.5,41875,tcp,FIN,-,NaN
699976,59.166.0.2,60849,149.171.126.7,53,udp,CON,-,NaN
699977,59.166.0.3,14472,149.171.126.5,39979,tcp,FIN,-,NaN
699978,59.166.0.3,18827,149.171.126.7,53,udp,CON,-,NaN
699979,59.166.0.8,24528,149.171.126.1,53,udp,CON,-,NaN
699980,59.166.0.4,19461,149.171.126.6,6881,tcp,FIN,-,NaN
699981,59.166.0.1,35327,149.171.126.5,80,tcp,FIN,-,NaN
699982,59.166.0.2,9969,149.171.126.9,8650,tcp,FIN,-,NaN
699983,59.166.0.8,33100,149.171.126.6,80,tcp,FIN,-,NaN
699984,59.166.0.3,12691,149.171.126.3,14273,tcp,FIN,-,NaN
699985,59.166.0.0,18895,149.171.126.9,80,tcp,FIN,-,NaN
699986,59.166.0.3,21661,149.171.126.0,80,tcp,FIN,-,NaN
699987,59.166.0.6,10213,149.171.126.3,46030,tcp,FIN,-,NaN
699988,59.166.0.6,31786,149.171.126.5,14228,udp,CON,-,NaN
699989,59.166.0.6,52262,149.171.126.5,51065,tcp,FIN,-,NaN
699990,59.166.0.4,28517,149.171.126.8,80,tcp,FIN,-,NaN
699991,59.166.0.8,34947,149.171.126.6,49439,tcp,FIN,-,NaN
699992,59.166.0.3,48114,149.171.126.3,53,udp,CON,dns,NaN
699993,59.166.0.3,48812,149.171.126.6,53,udp,CON,-,NaN
699994,59.166.0.3,48114,149.171.126.3,53,udp,CON,-,NaN
699995,59.166.0.6,8543,149.171.126.6,45536,tcp,FIN,-,NaN
699996,59.166.0.8,12520,149.171.126.6,31010,tcp,FIN,-,NaN
699997,59.166.0.0,18895,149.171.126.9,80,tcp,FIN,http,NaN
699998,59.166.0.0,30103,149.171.126.5,5190,tcp,FIN,-,NaN
699999,59.166.0.6,30388,149.171.126.5,111,udp,CON,-,NaN
700000,59.166.0.0,6055,149.171.126.5,54145,tcp,FIN,-,NaN

In [18]:
network_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700001 entries, 0 to 700000
Data columns (total 49 columns):
srcip               700001 non-null object
sport               700001 non-null object
dstip               700001 non-null object
dsport              700001 non-null object
proto               700001 non-null object
state               700001 non-null object
dur                 700001 non-null float64
sbytes              700001 non-null int64
dbytes              700001 non-null int64
sttl                700001 non-null int64
dttl                700001 non-null int64
sloss               700001 non-null int64
dloss               700001 non-null int64
service             700001 non-null object
Sload               700001 non-null float64
Dload               700001 non-null float64
Spkts               700001 non-null int64
Dpkts               700001 non-null int64
swin                700001 non-null int64
dwin                700001 non-null int64
stcpb               700001 non-null int64
dtcpb               700001 non-null int64
smeansz             700001 non-null int64
dmeansz             700001 non-null int64
trans_depth         700001 non-null int64
res_bdy_len         700001 non-null int64
Sjit                700001 non-null float64
Djit                700001 non-null float64
Stime               700001 non-null int64
Ltime               700001 non-null int64
Sintpkt             700001 non-null float64
Dintpkt             700001 non-null float64
tcprtt              700001 non-null float64
synack              700001 non-null float64
ackdat              700001 non-null float64
is_sm_ips_ports     700001 non-null int64
ct_state_ttl        700001 non-null int64
ct_flw_http_mthd    700001 non-null int64
is_ftp_login        700001 non-null int64
ct_ftp_cmd          700001 non-null int64
ct_srv_src          700001 non-null int64
ct_srv_dst          700001 non-null int64
ct_dst_ltm          700001 non-null int64
ct_src_ ltm         700001 non-null int64
ct_src_dport_ltm    700001 non-null int64
ct_dst_sport_ltm    700001 non-null int64
ct_dst_src_ltm      700001 non-null int64
attack_cat          22215 non-null object
Label               700001 non-null int64
dtypes: float64(10), int64(31), object(8)
memory usage: 261.7+ MB

In [19]:
network_data.Label.value_counts()

0    677786
1     22215
Name: Label, dtype: int64

In [20]:
network_data.dsport

53       107485
80        61279
5190      33429
53        29812
6881      28222
25        25071
111       23335
21        14979
22        14769
143       14589
80        13348
5190       7505
6881       6669
111        5611
25         5221
0          5085
0          4588
22         3306
21         2957
143        2869
179        2339
520        1082
179         728
445         656
49160       552
29644       530
2627        520
1512        499
52579       468
42035       466
          ...
21132         1
61017         1
61015         1
26153         1
9352          1
26155         1
27597         1
55396         1
56874         1
44225         1
33305         1
26165         1
26167         1
64001         1
33147         1
21765         1
37293         1
36151         1
60992         1
26175         1
53592         1
58700         1
9601          1
45891         1
2768          1
26184         1
60986         1
43943         1
60981         1
20563         1
Name: dsport, Length: 87819, dtype: int64

In [30]:
network_data.drop('attack_cat',axis=1,inplace=True)

In [54]:
def f(r):
    try:
        x = int(r)
    except:
        if r == '0x000b':
            x = 11
        if r == '0x000c':
            x = 12
        x = 99999
    finally:
        return x
    
network_data['sport'] = network_data.sport.map(f)

In [61]:
def f(r):
    try:
        x = int(r)
    except:
        x = 0
        x = int(r,16)
    finally:
        return x
    
network_data['dsport']  = network_data.dsport.map(f)

In [63]:
network_data.select_dtypes('object')

               srcip           dstip proto state service
0         59.166.0.0   149.171.126.6   udp   CON     dns
1         59.166.0.0   149.171.126.9   udp   CON       -
2         59.166.0.6   149.171.126.7   udp   CON     dns
3         59.166.0.5   149.171.126.5   udp   CON     dns
4         59.166.0.3   149.171.126.0   udp   CON     dns
5         59.166.0.0   149.171.126.9   udp   CON       -
6         59.166.0.6   149.171.126.4   udp   CON     dns
7        10.40.182.3     10.40.182.3   arp   INT       -
8         59.166.0.5   149.171.126.6   udp   CON     dns
9         59.166.0.7   149.171.126.4   udp   CON     dns
10       10.40.170.2     10.40.170.2   arp   INT       -
11       10.40.170.2     10.40.170.2   arp   INT       -
12       10.40.182.3     10.40.182.3   arp   INT       -
13        59.166.0.1   149.171.126.5   udp   CON     dns
14        59.166.0.1   149.171.126.9   udp   CON       -
15        59.166.0.1   149.171.126.6   udp   CON       -
16        59.166.0.2   149.171.126.4   udp   CON     dns
17        59.166.0.1   149.171.126.9   udp   CON       -
18        59.166.0.1   149.171.126.6   udp   CON       -
19        59.166.0.4   149.171.126.5   udp   CON     dns
20      175.45.176.3  149.171.126.18   udp   INT       -
21      175.45.176.2  149.171.126.16   tcp   FIN    http
22      175.45.176.0  149.171.126.16   tcp   FIN    http
23        59.166.0.3   149.171.126.9   udp   CON     dns
24        59.166.0.2   149.171.126.8   udp   CON     dns
25        59.166.0.8   149.171.126.2   udp   CON     dns
26        59.166.0.9   149.171.126.6   udp   CON     dns
27        59.166.0.0   149.171.126.1   udp   CON     dns
28        59.166.0.5   149.171.126.9   udp   CON     dns
29        59.166.0.7   149.171.126.4   udp   CON     dns
...              ...             ...   ...   ...     ...
699971    59.166.0.1   149.171.126.1   tcp   FIN       -
699972    59.166.0.7   149.171.126.1   tcp   FIN       -
699973    59.166.0.9   149.171.126.3   tcp   FIN       -
699974    59.166.0.0   149.171.126.8   udp   CON       -
699975    59.166.0.3   149.171.126.5   tcp   FIN       -
699976    59.166.0.2   149.171.126.7   udp   CON       -
699977    59.166.0.3   149.171.126.5   tcp   FIN       -
699978    59.166.0.3   149.171.126.7   udp   CON       -
699979    59.166.0.8   149.171.126.1   udp   CON       -
699980    59.166.0.4   149.171.126.6   tcp   FIN       -
699981    59.166.0.1   149.171.126.5   tcp   FIN       -
699982    59.166.0.2   149.171.126.9   tcp   FIN       -
699983    59.166.0.8   149.171.126.6   tcp   FIN       -
699984    59.166.0.3   149.171.126.3   tcp   FIN       -
699985    59.166.0.0   149.171.126.9   tcp   FIN       -
699986    59.166.0.3   149.171.126.0   tcp   FIN       -
699987    59.166.0.6   149.171.126.3   tcp   FIN       -
699988    59.166.0.6   149.171.126.5   udp   CON       -
699989    59.166.0.6   149.171.126.5   tcp   FIN       -
699990    59.166.0.4   149.171.126.8   tcp   FIN       -
699991    59.166.0.8   149.171.126.6   tcp   FIN       -
699992    59.166.0.3   149.171.126.3   udp   CON     dns
699993    59.166.0.3   149.171.126.6   udp   CON       -
699994    59.166.0.3   149.171.126.3   udp   CON       -
699995    59.166.0.6   149.171.126.6   tcp   FIN       -
699996    59.166.0.8   149.171.126.6   tcp   FIN       -
699997    59.166.0.0   149.171.126.9   tcp   FIN    http
699998    59.166.0.0   149.171.126.5   tcp   FIN       -
699999    59.166.0.6   149.171.126.5   udp   CON       -
700000    59.166.0.0   149.171.126.5   tcp   FIN       -

[700001 rows x 5 columns]

In [46]:
network_data.sport

0         False
1         False
2         False
3         False
4         False
5         False
6         False
7          True
8         False
9         False
10         True
11         True
12         True
13        False
14        False
15        False
16        False
17        False
18        False
19        False
20        False
21        False
22        False
23        False
24        False
25        False
26        False
27        False
28        False
29        False
          ...
699971    False
699972    False
699973    False
699974    False
699975    False
699976    False
699977    False
699978    False
699979    False
699980    False
699981    False
699982    False
699983    False
699984    False
699985    False
699986    False
699987    False
699988    False
699989    False
699990    False
699991    False
699992    False
699993    False
699994    False
699995    False
699996    False
699997    False
699998    False
699999    False
700000    False
Name: sport, Length: 700001, dtype: bool

In [48]:
network_data.sport == '0x00b'

0         False
1         False
2         False
3         False
4         False
5         False
6         False
7         False
8         False
9         False
10        False
11        False
12        False
13        False
14        False
15        False
16        False
17        False
18        False
19        False
20        False
21        False
22        False
23        False
24        False
25        False
26        False
27        False
28        False
29        False
          ...
699971    False
699972    False
699973    False
699974    False
699975    False
699976    False
699977    False
699978    False
699979    False
699980    False
699981    False
699982    False
699983    False
699984    False
699985    False
699986    False
699987    False
699988    False
699989    False
699990    False
699991    False
699992    False
699993    False
699994    False
699995    False
699996    False
699997    False
699998    False
699999    False
700000    False
Name: sport, Length: 700001, dtype: bool

In [64]:
network_data.proto.unique()

array(['udp', 'arp', 'tcp', 'ospf', 'icmp', 'igmp', 'sctp', 'udt', 'sep',
       'sun-nd', 'swipe', 'mobile', 'pim', 'rtp', 'ipnip', 'ip', 'ggp',
       'st2', 'egp', 'cbt', 'emcon', 'nvp', 'igp', 'xnet', 'argus',
       'bbn-rcc', 'chaos', 'pup', 'hmp', 'mux', 'dcn', 'prm', 'trunk-1',
       'xns-idp', 'trunk-2', 'leaf-1', 'leaf-2', 'irtp', 'rdp', 'iso-tp4',
       'netblt', 'mfe-nsp', 'merit-inp', '3pc', 'xtp', 'idpr', 'tp++',
       'ddp', 'idpr-cmtp', 'ipv6', 'il', 'idrp', 'ipv6-frag', 'sdrp',
       'ipv6-route', 'gre', 'rsvp', 'mhrp', 'bna', 'esp', 'i-nlsp',
       'narp', 'ipv6-no', 'tlsp', 'skip', 'ipv6-opts', 'any', 'cftp',
       'sat-expak', 'kryptolan', 'rvd', 'ippc', 'sat-mon', 'ipcv', 'visa',
       'cpnx', 'cphb', 'wsn', 'pvp', 'br-sat-mon', 'wb-mon', 'wb-expak',
       'iso-ip', 'secure-vmtp', 'vmtp', 'vines', 'ttp', 'nsfnet-igp',
       'dgp', 'tcf', 'eigrp', 'sprite-rpc', 'larp', 'mtp', 'ax.25',
       'ipip', 'micp', 'aes-sp3-d', 'encap', 'etherip', 'pri-enc', 'gmtp',
       'pnni', 'ifmp', 'aris', 'qnx', 'a/n', 'scps', 'snp', 'ipcomp',
       'compaq-peer', 'ipx-n-ip', 'vrrp', 'zero', 'pgm', 'iatp', 'ddx',
       'l2tp', 'srp', 'stp', 'smp', 'uti', 'sm', 'ptp', 'fire', 'crtp',
       'isis', 'crudp', 'sccopmce', 'sps', 'pipe', 'iplt', 'unas', 'fc',
       'ib'], dtype=object)